## baselines
## Random init MLP
feat_hand_crafted: false
feat_random_cnn: false

# trained networks
model_path: /data/UKBB/SSL/day_sec_10k/logs/models
flip_net: false
flip_net_ft: true
flip_net_random_mlp: true
load_weights: false
freeze_weight: false
flip_net_path: "${evaluation.model_path}/mtl_baseline_rotationFalse_timeTrue_data1_lr0.0001_30-03-2021_22:28:08.mdl"
input_size: 300    # input size after resampling the raw data
epoch_idx: 0

# hyper-parameters
learning_rate: 0.0001
num_workers: 6
patience: 5
num_epoch: 250
subR: 1

evaluation_name: flip_net_random_mlp
