defaults:
  - _self_
  - model: vgg
  - data: ukbb_10k
  - task: all
  - augmentation: all
  - dataloader: default

runtime:
  gpu: -1
  gpu_ids: [0, 1, 2, 3]  # if more than one gpu
  distributed: False
  multi_gpu: False
  num_epoch: 200
  is_epoch_data: False
